--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: helloworld-canary
spec: 
  minReadySeconds: 5
  replicas: 1
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels: 
        app: helloworld
        track: canary
    spec: 
      containers: 
        - name: helloworld
          image: "supergiantkir/animals:moose"
          ports: 
            - containerPort: 80
          resources: 
            limits: 
              cpu: 100m
            requests: 
              cpu: 50m
